version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  auth-service:
    build:
      dockerfile: Dockerfile
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8004:8004"
    restart: always

  accademic-service:
    build:
      dockerfile: Dockerfile
      context: ./accademic-service
    container_name: accademic-service
    ports:
      - "8006:8006"
    restart: always
  
  user-service:
    build:
      dockerfile: Dockerfile
      context: ./user-service
    container_name: user-service
    ports:
      - "8005:8005"
    restart: always

  notice-service:
    build:
      dockerfile: Dockerfile
      context: ./notice-service
    container_name: notice-service
    ports:
      - "8007:8007"
    restart: always

  payment-service:
    build:
      dockerfile: Dockerfile
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8008:8008"
    restart: always    

  client:
    build:
      dockerfile: Dockerfile
      context: ./client 
    container_name: client
    ports:
      - "3000:3000" 
    restart: on-failure

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - auth-service
      - accademic-service
      - user-service
      - notice-service
      - payment-service
    ports:
      - 8080:80
